var a0 = [
  "Class 1 math (India)",
  "Class 2 math (India)",
  "Class 3 math (India)",
  "Class 4 math (India)",
  "Class 5 math (India)",
  "Class 6 math (India)",
  "Class 7 math (India)",
  "Class 8 math (India)",
  "Class 9 math (India)",
  "Class 10 math (India)",
  "Class 11 math (India)",
  "Class 12 math (India)",
];

var maths_text = [
  "Course summary",
  "Class 1 math (India)",
  "Class 2 math (India)",
  "Class 3 math (India)",
  "Class 4 math (India)",
  "Class 5 math (India)",
  "Class 6 math (India)",
  "Class 7 math (India)",
  "Class 8 math (India)",
  "Class 9 math (India)",
  "Class 10 math (India)",
  "Class 11 math (India)",
  "Class 12 math (India)",
  "Class 1 math (India)",
  "Number from 1 to 9",
  "Number from 10 to 20",
  "Number from 1 to 100",
  "Geometry and measurement",
  "Class 2 math (India)",
  "Numbers from 1 to 100",
  "Addition and subtraction without regrouping",
  "Addition and subtraction with regrouping",
  "Geometry and measurement",
  "Class 3 math (India)",
  "Numbers from 1 to 1000",
  "Addition and subtraction without regrouping",
  "Addition and subtraction with regrouping",
  "Multiplication",
  "Division",
  "Smart charts",
  "Geometry and measurement",
  "Class 4 math (India)",
  "Addition and subtraction",
  "Multiplication",
  "Division",
  "Smart charts",
  "Halves and quarters",
  "Geometry and measurement",
  "Class 5 math (India)",
  "Addition and subtraction",
  "Multiplication",
  "Division",
  "Parts and wholes",
  "Tenths and Hundredths",
  "Factors and multiples",
  "Smarts charts",
  "How big? How heavy?"
      "Shapes and angles",
  "Area and its boundary",
  "Identify patterns",
  "Class 6 math (India)",
  "Knowing our numbers",
  "Whole numbers",
  "Playing with numbers",
  "Basic geometrical ideas",
  "Understanding elementary shapes",
  "Integers",
  "Fractions",
  "Decimals",
  "Data handling",
  "Mensuration",
  "Algebra",
  "Ratio and proportion",
  "Class 7 math (India)",
  "Integers",
  "Fractions and decimals",
  "Data handling",
  "Simple equations",
  "Lines and angles",
  "The triangle and its properties",
  "Congruence of triangles",
  "Comparing quantities",
  "Rational numbers",
  "Perimeter and area",
  "Exponents and powers",
  "Algebraic expressions",
  "Class 8 math (India)",
  "Rational numbers",
  "Linear equations in one variable",
  "Understanding quadrilaterals",
  "Data handling",
  "Squares and square roots",
  "Cubes and cube roots",
  "Comparing quantities",
  "Algebraic expressions and identities",
  "Visualising solid shapes",
  "Mensuration",
  "Exponents and powers",
  "Factorisation",
  "Introduction to graphs",
  "Playing with numbers",
  "Class 9 math (India)",
  "Number systems",
  "Polynomials",
  "Coordinate geometry",
  "Linear equations in two variables",
  "Lines and angles",
  "Triangles",
  "Quadrilaterals",
  "Areas of parallelograms and triangles",
  "Circles",
  "Surface areas and volumes",
  "Statistics",
  "Probability",
  "Class 10 math (India)",
  "Real numbers",
  "Polynomials",
  "Pair of linear equations in two variables",
  "Quadratic equations",
  "Arithmetic progressions",
  "Triangles",
  "Coordinate geometry",
  "Introduction to trigonometry",
  "Some applications of trigonometry",
  "Circles",
  "Areas related to circles",
  "Surface areas and volumes",
  "Statistics",
  "Probability",
  "Class 11 math (India)",
  "Sets",
  "Relations and functions",
  "Trigonometric functions",
  "Complex numbers",
  "Linear inequalities",
  "Permutations and combinations",
  "Binomial theorem",
  "Sequence and series",
  "Straight lines",
  "Conic sections",
  "Introduction to three dimensional geometry",
  "Limits",
  "Derivatives",
  "Statistics",
  "Probability",
  "Class 12 math (India)",
  "Relations and functions",
  "Inverse trigonometric functions",
  "Matrices",
  "Determinants",
  "Continuity & differentiability",
  "Advanced differentiation",
  "Playing with graphs (using differentiation)",
  "Applications of derivatives",
  "Indefinite Integrals",
  "Definite Integrals",
  "Application of integrals",
  "Differential equations",
  "Vector algebra",
  "Three dimensional geometry",
  "Probability",
  "Class 1 math (India)",
  "Numbers from 1 to 9",
  "Counting small numbers",
  "Comparing small numbers",
  "What is additions?",
  "Making small numbers",
  "Making 10",
  "What is subtraction?",
  "Subtract within 10",
  "Relate addition and subtraction",
  "Addition and subtraction word problems",
  "Numbers from 10 to 20",
  "Counting numbers from 1 to 20",
  "Counting objects",
  "Addition within 20",
  "Subtraction within 20",
  "Equal sign",
  "Missing numbers within 20",
  "Repeated addition",
  "Word problems within 20",
  "Word problems with 'more' and 'fewer'",
  "Numbers from 1 to 100",
  "Counting numbers to 100",
  "Counting by tens",
  "Place value",
  "Comparing 2-digit numbers",
  "Geometry and measurement",
  "Shapes and spaces",
  "Length and size",
  "Class 2 math (India)",
  "Numbers from 1 to 100",
  "Counting numbers to 100",
  "Place value",
  "Comparing 2-digit numbers",
  "Addition and subtraction without regrouping",
  "Adding 1s and 10s",
  "Subtracing 1s and 10s",
  "Adding without regrouping",
  "Subtracing without regrouping",
  "Addition and subtraction using number line",
  "Addition and subtraction with regrouping",
  "Adding with regrouping",
  "Subtracting with regrouping",
  "Addition and subtraction mixed problems",
  "Word problems with 100",
  "'Fewer' and 'More' word problems",
  "Geometry and measurement",
  "Length",
  "Mass",
  "Volume",
  "Class 3 math (India)",
  "Numbers from 1 to 1000",
  "Place value",
  "Comparing 3-digit numbers",
  "Skip counting",
  "Addition and subtraction without regrouping",
  "Adding 1s, 10s and 100s",
  "Subtracting 1s, 10s, and 100s",
  "Adding and subtracting by breaking apart",
  "Adding and subtracting using number line",
  "Addition and subtraction with regrouping",
  "Adding by regrouping",
  "Subtracting by regrouping",
  "Adding and subtracting missing value problems",
  "Addition and subtraction word problems",
  "Multiplication",
  "Intro to multiplication",
  "Multiplication problems",
  "Multiplication word problems",
  "Multiply by 10s",
  "Multiply 2-digit numbers with area model",
  "Division",
  "Intro to division",
  "Divide by 1,2,4,5, or 10",
  "Divide by 3 or 6",
  "Divide by 7, 8, or 9",
  "Division word problems",
  "Smart charts",
  "Picture graphs",
  "Geometry and measurement",
  "Length",
  "Volume",
  "Mass",
  "Class 4 math (India)",
  "Addition and subtraction",
  "3-digit addition",
  "3-digit subtraction",
  "Multiplication",
  "Multiply by using area model",
  "Multiply by using distributive property",
  "Multiply by 1-digit numbers",
  "Multi-digit multiplication",
  "Division",
  "Relate multiplication and division",
  "Division: place value and area",
  "Divide by 1 digit numbrs",
  "Multi digit division (no remainders)",
  "Smart charts",
  "Picture graphs",
  "Bar charts",
  "Halves and quarters",
  "Fractions of shapes",
  "Geometry and measurement",
  "Length",
  "Volume",
  "Mass",
  "Time",
  "Perimeter",
  "Area",
  "Class 5 math (India)",
  "Addition and subtraction",
  "Multi-digit addition",
  "Multi-digit subtraction",
  "Multiplication",
  "Multiply by using standard algorithm",
  "Multiply by 1-digit numbers",
  "Multi-digit multiplication",
  "Division",
  "Multi-digit division (no remainders)",
  "Remainders",
  "Multi-digit division (remainders)",
  "Parts and wholes",
  "Intro to fractions",
  "Recognise fractions",
  "Understanding numerators and denominators",
  "Fractions word problems",
  "Equivalent fractions",
  "Tenths and Hundredths",
  "Intro to decimals",
  "Decimals on the number line",
  "Decimals as fractions",
  "Comparing decimals",
  "Factors and multiples",
  "Factors",
  "Multiples",
  "Smart charts",
  "Picture graphs",
  "Bar graphs",
  "How big? How heavy?",
  "Length",
  "Volume",
  "Mass",
  "Conversions",
  "Shapes and angles",
  "Angle introduction",
  "Measuring angles",
  "Angle types",
  "Area and its boundary",
  "Count unit squares to find area",
  "Creating rectangles with given area",
  "Area of rectangles",
  "Area of rectangles more problems",
  "Intro to perimeter",
  "Identify patterns",
  "Patterns 1",
  "Patterns 2",
  "Class 6 math (India)",
  "Knowing our numbers",
  "Comparing numbers",
  "Large numbers",
  "Large numbers in practice",
  "Estimating to nearest ten, hundred, or thousand",
  "Estimating sum, difference, or product",
  "Using brackets",
  "Roman numerals",
  "Whole numbers",
  "Whole numbers on the number",
  "Add, subtract, and multiply on the number line",
  "Commutative property",
  "Associative property",
  "Distributive property",
  "Identity properties of 0 and 1",
  "Playing with numbers",
  "Factors and multiples",
  "Prime and composite numbers",
  "Tests for divisibility",
  "Common factors and common multiples",
  "Some more divisibility rules",
  "Prime factorisation",
  "Highest common factor",
  "Lowest common multiple",
  "Some problems on HCF and LCM",
  "Basic geometrical ideas",
  "Lines, line segments, and rays",
  "Curves and polygons",
  "Angles",
  "Circle",
  "Understanding elementary shapes",
  "Measuring line segments and angles",
  "Types of angles",
  "Parallel and perpendicular lines",
  "Classification of triangles",
  "Quadrilaterals",
  "Three dimensional shapes",
  "Integers",
  "Integers on the number line",
  "Ordering of integers",
  "Adding and subtracting integers",
  "Fractions",
  "Fractions on the number line",
  "Improper and mixed fractions",
  "Equivalent fractions",
  "Comparing fractions",
  "Adding or subtracting like fractions",
  "Adding or subtracting unlike fractions",
  "Fractions word problems",
  "Visualising fractions (bonus)",
  "Decimals",
  "Decimals on the number line",
  "Decimals as fractions",
  "Comparing decimals",
  "Addition of numbers with decimals",
  "Subtraction of decimals",
  "Decimals word problems",
  "Data handling",
  "Recording and organising data",
  "Pictographs",
  "Bar graphs",
  "Mensuration",
  "Perimeter",
  "Area",
  "Area of composite figures",
  "Mensuration word problems",
  "Algebra",
  "The idea of a variable",
  "Expressions with variables",
  "Using expressions practically",
  "Solution of an equations",
  "Ratio and proportion",
  "Ratio",
  "Proportion",
  "Unitary method",
  "Class 7 math (India)",
  "Integers",
  "Addition and subtraction of integers (Recap)",
  "Multiplication of integers",
  "Division of integers",
  "Integers word problems",
  "Fractions and decimals",
  "Fractions (Recap)",
  "Multiplying fractions",
  "Dividing fractions",
  "Fractions word problems",
  "Decimals (Recap)",
  "Multiplying decimals",
  "Dividing decimals",
  "Decimals word problems",
  "Data handling",
  "Mean, median, mode, range",
  "Use of bar graphs",
  "Probability",
  "Simple equations",
  "Setting up an equation (Recap)",
  "Solving an equation",
  "More equations",
  "Linear equations word problems",
  "Lines and angles",
  "Related angles",
  "Pair of lines",
  "The triangle and its properties",
  "Medians and altitudes",
  "Exterior angle property",
  "Angle sum property",
  "Two special triangles: Equilateral and isosceles",
  "Sum of the lengths of two sides",
  "Pythagoras theorem",
  "Congruence of triangles",
  "Congruence of triangles",
  "Criteria for congruence of triangles",
  "Comparing quantities",
  "Ratios (Recap)",
  "Meaning of percentage",
  "Percentage conversions",
  "Percentage word problems",
  "Profit or loss as a percentage",
  "Simple interest",
  "Rational numbers",
  "What are rational numbers?",
  "Comparison of rational numbers",
  "Rational numbers between two rational numbers",
  "Operations on rational numbers",
  "Perimeter and area",
  "Squares and rectangles",
  "Area of a parallelogram",
  "Area of a triangle",
  "Circles",
  "Conversion of units",
  "Applications",
  "Exponents and powers",
  "Intro to exponents",
  "Laws of exponents",
  "Using laws of exponents",
  "Large numbers in standard form",
  "Algebraic expressions",
  "Terms of an expression",
  "Combining like terms",
  "Addition and subtraction of algebraic expression",
  "Finding the value of an expression",
  "Class 8 math (India)",
  "Rational numbers",
  "The role of 0 and 1",
  "Distributive property",
  "Rational numbers on the number line",
  "Rational numbers between two rational numbers",
  "Linear equations in one variable",
  "Solving equations with variable on one side",
  "Solving equations with variable on both sides",
  "Equations reducible to linear form",
  "Linear equations word problems",
  "Understanding quadrilaterals",
  "Polygons",
  "Angle sum property",
  "Kinds of quadrilaterals",
  "Properties of a parallelogram",
  "Some special parallelograms",
  "Data handling",
  "Looking for information (Recap)",
  "Organising data",
  "Histograms",
  "Pie charts",
  "Squares and square roots",
  "Square roots using factorisation",
  "Numbers that are not perfect squares",
  "Square roots using long division",
  "Estimating square roots",
  "Cubes and cube roots",
  "Cube roots using factorisation",
  "Numbers that are not perfect cubes",
  "Cube roots using long division",
  "Comparing quantities",
  "Percent change word problems",
  "Profit and loss",
  "Tax and discount",
  "Compound interest",
  "Algebraic expressions and identities",
  "Addition and subtraction",
  "Multiplying monomials by monomials",
  "Multiplying monomials by polynomials",
  "Multiplying binomials",
  "Standard identities",
  "Polynomials word problems",
  "Visualising solid shapes",
  "Faces, edges, and vertices",
  "Mensuration",
  "Area of a trapezium",
  "Area of a polygon",
  "Cube and cuboid",
  "Cylinder",
  "Exponents and powers",
  "Laws of exponents (Recap)",
  "Negative exponents",
  "Laws of exponents (More practice)",
  "Numbers in standard form",
  "Factorisation",
  "Factors of a monomial",
  "Factorisation using common factors",
  "Factorisation using identities",
  "Factors of the form (x+a)(x+b)",
  "Dividing polynomials by monomials",
  "Dividing polynomials by polynomials",
  "Introduction to graphs",
  "Coordinates",
  "Distance between points in the first quadrant",
  "Playing with numbers",
  "Test for divisibility",
  "Some more divisibility tests",
  "Class 9 math (India)",
  "Number systems",
  "Irrational numbers",
  "Real numbers and their decimal expansions",
  "Operations on real numbers",
  "Simplifying expressions",
  "Laws of exponents for real numbers",
  "Polynomials",
  "Polynomials in one variable",
  "Zeros of a polynomial",
  "Remainder theorem",
  "Factorisation of polynomials",
  "Multiplying polynomials",
  "Standard identities",
  "Algebraic identities",
  "Coordinate geometry",
  "Cartesian system",
  "Plotting points on cartesian plane",
  "Linear equations in two variables",
  "Solutions of a linear equation",
  "Graph of a linear equation in two variables",
  "Lines and angles",
  "Pairs of angles",
  "Parallel lines and a transversal",
  "Lines parallel to the same line",
  "Angle sum property of a triangle",
  "Proofs: Lines and angles",
  "Triangles",
  "Triangles (review)",
  "Pythagorean theorem",
  "Criteria for congruence of triangles",
  "Proofs: Triangles",
  "Inequalities in a triangle",
  "Quadrilaterals",
  "Kinds of quadrilaterals",
  "Proofs: Parallelograms",
  "Proofs: Rhombus",
  "Proofs: Kite",
  "Areas of parallelograms and triangles",
  "Area of a parallelogram",
  "Area of a triangle",
  "Circles",
  "Circles and its related terms",
  "Angle subtended by a chord/arc of a circle",
  "Perpendicular from the centre to a chord",
  "Cyclic quadrilaterals",
  "Inscribed shapes problem solving",
  "Surface areas and volumes",
  "Heron's formula",
  "Cube, cuboid, and cylinder",
  "Cones and spheres",
  "Statistics",
  "Bar graphs",
  "Histograms",
  "Mean, median, mode, range",
  "Probability",
  "Experimental probability",
  "Probability problems",
  "Class 10 math (math)",
  "Real numbers",
  "Euclid's division algorithm",
  "Fundamental theorem of arithmetic",
  "HCF and LCM",
  "Proofs: Irrational numbers",
  "Rational numbers and their decimal expansions",
  "Polynomials",
  "Geometrical meaning of the zeros of a polynomial",
  "Relationship between zeros and coefficients",
  "Division algorithm for polynomials",
  "Pair of linear equations in two variables",
  "Graphical method",
  "Algebraic methods",
  "Number of solutions algebraically",
  "Equations reducible to linear form",
  "Linear equations word problems",
  "Quadratic equations",
  "Solving equations by factorizing",
  "Solving equations by completing the square",
  "Solving equations using the quadratic formula",
  "Nature of roots",
  "Quadratic equations word problems",
  "Arithmetic progressions",
  "Intro to arithmetic progressions",
  "Common difference of an AP",
  "nth term of an AP",
  "Sum of first n terms of an AP",
  "AP word problems "
];
