var a0 = [
  "Class 1 math (India)",
  "Class 2 math (India)",
  "Class 3 math (India)",
  "Class 4 math (India)",
  "Class 5 math (India)",
  "Class 6 math (India)",
  "Class 7 math (India)",
  "Class 8 math (India)",
  "Class 9 math (India)",
  "Class 10 math (India)",
  "Class 11 math (India)",
  "Class 12 math (India)",
];

var maths_text = [
  "Course summary",
  "Class 1 math (India)",
  "Class 2 math (India)",
  "Class 3 math (India)",
  "Class 4 math (India)",
  "Class 5 math (India)",
  "Class 6 math (India)",
  "Class 7 math (India)",
  "Class 8 math (India)",
  "Class 9 math (India)",
  "Class 10 math (India)",
  "Class 11 math (India)",
  "Class 12 math (India)",
  "Class 1 math (India)",
  "Number from 1 to 9",
  "Number from 10 to 20",
  "Number from 1 to 100",
  "Geometry and measurement",
  "Class 2 math (India)",
  "Numbers from 1 to 100",
  "Addition and subtraction without regrouping",
  "Addition and subtraction with regrouping",
  "Geometry and measurement",
  "Class 3 math (India)",
  "Numbers from 1 to 1000",
  "Addition and subtraction without regrouping",
  "Addition and subtraction with regrouping",
  "Multiplication",
  "Division",
  "Smart charts",
  "Geometry and measurement",
  "Class 4 math (India)",
  "Addition and subtraction",
  "Multiplication",
  "Division",
  "Smart charts",
  "Halves and quarters",
  "Geometry and measurement",
  "Class 5 math (India)",
  "Addition and subtraction",
  "Multiplication",
  "Division",
  "Parts and wholes",
  "Tenths and Hundredths",
  "Factors and multiples",
  "Smarts charts",
  "How big? How heavy?"
      "Shapes and angles",
  "Area and its boundary",
  "Identify patterns",
  "Class 6 math (India)",
  "Knowing our numbers",
  "Whole numbers",
  "Playing with numbers",
  "Basic geometrical ideas",
  "Understanding elementary shapes",
  "Integers",
  "Fractions",
  "Decimals",
  "Data handling",
  "Mensuration",
  "Algebra",
  "Ratio and proportion",
  "Class 7 math (India)",
  "Integers",
  "Fractions and decimals",
  "Data handling",
  "Simple equations",
  "Lines and angles",
  "The triangle and its properties",
  "Congruence of triangles",
  "Comparing quantities",
  "Rational numbers",
  "Perimeter and area",
  "Exponents and powers",
  "Algebraic expressions",
  "Class 8 math (India)",
  "Rational numbers",
  "Linear equations in one variable",
  "Understanding quadrilaterals",
  "Data handling",
  "Squares and square roots",
  "Cubes and cube roots",
  "Comparing quantities",
  "Algebraic expressions and identities",
  "Visualising solid shapes",
  "Mensuration",
  "Exponents and powers",
  "Factorisation",
  "Introduction to graphs",
  "Playing with numbers",
  "Class 9 math (India)",
  "Number systems",
  "Polynomials",
  "Coordinate geometry",
  "Linear equations in two variables",
  "Lines and angles",
  "Triangles",
  "Quadrilaterals",
  "Areas of parallelograms and triangles",
  "Circles",
  "Surface areas and volumes",
  "Statistics",
  "Probability",
  "Class 10 math (India)",
  "Real numbers",
  "Polynomials",
  "Pair of linear equations in two variables",
  "Quadratic equations",
  "Arithmetic progressions",
  "Triangles",
  "Coordinate geometry",
  "Introduction to trigonometry",
  "Some applications of trigonometry",
  "Circles",
  "Areas related to circles",
  "Surface areas and volumes",
  "Statistics",
  "Probability",
  "Class 11 math (India)",
  "Sets",
  "Relations and functions",
  "Trigonometric functions",
  "Complex numbers",
  "Linear inequalities",
  "Permutations and combinations",
  "Binomial theorem",
  "Sequence and series",
  "Straight lines",
  "Conic sections",
  "Introduction to three dimensional geometry",
  "Limits",
  "Derivatives",
  "Statistics",
  "Probability",
  "Class 12 math (India)",
  "Relations and functions",
  "Inverse trigonometric functions",
  "Matrices",
  "Determinants",
  "Continuity & differentiability",
  "Advanced differentiation",
  "Playing with graphs (using differentiation)",
  "Applications of derivatives",
  "Indefinite Integrals",
  "Definite Integrals",
  "Application of integrals",
  "Differential equations",
  "Vector algebra",
  "Three dimensional geometry",
  "Probability",
  "Class 1 math (India)",
  "Numbers from 1 to 9",
  "Counting small numbers",
  "Comparing small numbers",
  "What is additions?",
  "Making small numbers",
  "Making 10",
  "What is subtraction?",
  "Subtract within 10",
  "Relate addition and subtraction",
  "Addition and subtraction word problems",
  "Numbers from 10 to 20",
  "Counting numbers from 1 to 20",
  "Counting objects",
  "Addition within 20",
  "Subtraction within 20",
  "Equal sign",
  "Missing numbers within 20",
  "Repeated addition",
  "Word problems within 20",
  "Word problems with 'more' and 'fewer'",
  "Numbers from 1 to 100",
  "Counting numbers to 100",
  "Counting by tens",
  "Place value",
  "Comparing 2-digit numbers",
  "Geometry and measurement",
  "Shapes and spaces",
  "Length and size",
  "Class 2 math (India)",
  "Numbers from 1 to 100",
  "Counting numbers to 100",
  "Place value",
  "Comparing 2-digit numbers",
  "Addition and subtraction without regrouping",
  "Adding 1s and 10s",
  "Subtracing 1s and 10s",
  "Adding without regrouping",
  "Subtracing without regrouping",
  "Addition and subtraction using number line",
  "Addition and subtraction with regrouping",
  "Adding with regrouping",
  "Subtracting with regrouping",
  "Addition and subtraction mixed problems",
  "Word problems with 100",
  "'Fewer' and 'More' word problems",
  "Geometry and measurement",
  "Length",
  "Mass",
  "Volume",
  "Class 3 math (India)",
  "Numbers from 1 to 1000",
  "Place value",
  "Comparing 3-digit numbers",
  "Skip counting",
  "Addition and subtraction without regrouping",
  "Adding 1s, 10s and 100s",
  "Subtracting 1s, 10s, and 100s",
  "Adding and subtracting by breaking apart",
  "Adding and subtracting using number line",
  "Addition and subtraction with regrouping",
  "Adding by regrouping",
  "Subtracting by regrouping",
  "Adding and subtracting missing value problems",
  "Addition and subtraction word problems",
  "Multiplication",
  "Intro to multiplication",
  "Multiplication problems",
  "Multiplication word problems",
  "Multiply by 10s",
  "Multiply 2-digit numbers with area model",
  "Division",
  "Intro to division",
  "Divide by 1,2,4,5, or 10",
  "Divide by 3 or 6",
  "Divide by 7, 8, or 9",
  "Division word problems",
  "Smart charts",
  "Picture graphs",
  "Geometry and measurement",
  "Length",
  "Volume",
  "Mass",
  "Class 4 math (India)",
  "Addition and subtraction",
  "3-digit addition",
  "3-digit subtraction",
  "Multiplication",
  "Multiply by using area model",
  "Multiply by using distributive property",
  "Multiply by 1-digit numbers",
  "Multi-digit multiplication",
  "Division",
  "Relate multiplication and division",
  "Division: place value and area",
  "Divide by 1 digit numbrs",
  "Multi digit division (no remainders)",
  "Smart charts",
  "Picture graphs",
  "Bar charts",
  "Halves and quarters",
  "Fractions of shapes",
  "Geometry and measurement",
  "Length",
  "Volume",
  "Mass",
  "Time",
  "Perimeter",
  "Area",
  "Class 5 math (India)",
  "Addition and subtraction",
  "Multi-digit addition",
  "Multi-digit subtraction",
  "Multiplication",
  "Multiply by using standard algorithm",
  "Multiply by 1-digit numbers",
  "Multi-digit multiplication",
  "Division",
  "Multi-digit division (no remainders)",
  "Remainders",
  "Multi-digit division (remainders)",
  "Parts and wholes",
  "Intro to fractions",
  "Recognise fractions",
  "Understanding numerators and denominators",
  "Fractions word problems",
  "Equivalent fractions",
  "Tenths and Hundredths",
  "Intro to decimals",
  "Decimals on the number line",
  "Decimals as fractions",
  "Comparing decimals",
  "Factors and multiples",
  "Factors",
  "Multiples",
  "Smart charts",
  "Picture graphs",
  "Bar graphs",
  "How big? How heavy?",
  "Length",
  "Volume",
  "Mass",
  "Conversions",
  "Shapes and angles",
  "Angle introduction",
  "Measuring angles",
  "Angle types",
  "Area and its boundary",
  "Count unit squares to find area",
  "Creating rectangles with given area",
  "Area of rectangles",
  "Area of rectangles more problems",
  "Intro to perimeter",
  "Identify patterns",
  "Patterns 1",
  "Patterns 2",
  "Class 6 math (India)",
  "Knowing our numbers",
  "Comparing numbers",
  "Large numbers",
  "Large numbers in practice",
  "Estimating to nearest ten, hundred, or thousand",
  "Estimating sum, difference, or product",
  "Using brackets",
  "Roman numerals",
  "Whole numbers",
  "Whole numbers on the number",
  "Add, subtract, and multiply on the number line",
  "Commutative property",
  "Associative property",
  "Distributive property",
  "Identity properties of 0 and 1",
  "Playing with numbers",
  "Factors and multiples",
  "Prime and composite numbers",
  "Tests for divisibility",
  "Common factors and common multiples",
  "Some more divisibility rules",
  "Prime factorisation",
  "Highest common factor",
  "Lowest common multiple",
  "Some problems on HCF and LCM",
  "Basic geometrical ideas",
  "Lines, line segments, and rays",
  "Curves and polygons",
  "Angles",
  "Circle",
  "Understanding elementary shapes",
  "Measuring line segments and angles",
  "Types of angles",
  "Parallel and perpendicular lines",
  "Classification of triangles",
  "Quadrilaterals",
  "Three dimensional shapes",
  "Integers",
  "Integers on the number line",
  "Ordering of integers",
  "Adding and subtracting integers",
  "Fractions",
  "Fractions on the number line",
  "Improper and mixed fractions",
  "Equivalent fractions",
  "Comparing fractions",
  "Adding or subtracting like fractions",
  "Adding or subtracting unlike fractions",
  "Fractions word problems",
  "Visualising fractions (bonus)",
  "Decimals",
  "Decimals on the number line",
  "Decimals as fractions",
  "Comparing decimals",
  "Addition of numbers with decimals",
  "Subtraction of decimals",
  "Decimals word problems",
  "Data handling",
  "Recording and organising data",
  "Pictographs",
  "Bar graphs",
  "Mensuration",
  "Perimeter",
  "Area",
  "Area of composite figures",
  "Mensuration word problems",
  "Algebra",
  "The idea of a variable",
  "Expressions with variables",
  "Using expressions practically",
  "Solution of an equations",
  "Ratio and proportion",
  "Ratio",
  "Proportion",
  "Unitary method",
  "Class 7 math (India)",
  "Integers",
  "Addition and subtraction of integers (Recap)",
  "Multiplication of integers",
  "Division of integers",
  "Integers word problems",
  "Fractions and decimals",
  "Fractions (Recap)",
  "Multiplying fractions",
  "Dividing fractions",
  "Fractions word problems",
  "Decimals (Recap)",
  "Multiplying decimals",
  "Dividing decimals",
  "Decimals word problems",
  "Data handling",
  "Mean, median, mode, range",
  "Use of bar graphs",
  "Probability",
  "Simple equations",
  "Setting up an equation (Recap)",
  "Solving an equation",
  "More equations",
  "Linear equations word problems",
  "Lines and angles",
  "Related angles",
  "Pair of lines",
  "The triangle and its properties",
  "Medians and altitudes",
  "Exterior angle property",
  "Angle sum property",
  "Two special triangles: Equilateral and isosceles",
  "Sum of the lengths of two sides",
  "Pythagoras theorem",
  "Congruence of triangles",
  "Congruence of triangles",
  "Criteria for congruence of triangles",
  "Comparing quantities",
  "Ratios (Recap)",
  "Meaning of percentage",
  "Percentage conversions",
  "Percentage word problems",
  "Profit or loss as a percentage",
  "Simple interest",
  "Rational numbers",
  "What are rational numbers?",
  "Comparison of rational numbers",
  "Rational numbers between two rational numbers",
  "Operations on rational numbers",
  "Perimeter and area",
  "Squares and rectangles",
  "Area of a parallelogram",
  "Area of a triangle",
  "Circles",
  "Conversion of units",
  "Applications",
  "Exponents and powers",
  "Intro to exponents",
  "Laws of exponents",
  "Using laws of exponents",
  "Large numbers in standard form",
  "Algebraic expressions",
  "Terms of an expression",
  "Combining like terms",
  "Addition and subtraction of algebraic expression",
  "Finding the value of an expression",
  "Class 8 math (India)",
  "Rational numbers",
  "The role of 0 and 1",
  "Distributive property",
  "Rational numbers on the number line",
  "Rational numbers between two rational numbers",
  "Linear equations in one variable",
  "Solving equations with variable on one side",
  "Solving equations with variable on both sides",
  "Equations reducible to linear form",
  "Linear equations word problems",
  "Understanding quadrilaterals",
  "Polygons",
  "Angle sum property",
  "Kinds of quadrilaterals",
  "Properties of a parallelogram",
  "Some special parallelograms",
  "Data handling",
  "Looking for information (Recap)",
  "Organising data",
  "Histograms",
  "Pie charts",
  "Squares and square roots",
  "Square roots using factorisation",
  "Numbers that are not perfect squares",
  "Square roots using long division",
  "Estimating square roots",
  "Cubes and cube roots",
  "Cube roots using factorisation",
  "Numbers that are not perfect cubes",
  "Cube roots using long division",
  "Comparing quantities",
  "Percent change word problems",
  "Profit and loss",
  "Tax and discount",
  "Compound interest",
  "Algebraic expressions and identities",
  "Addition and subtraction",
  "Multiplying monomials by monomials",
  "Multiplying monomials by polynomials",
  "Multiplying binomials",
  "Standard identities",
  "Polynomials word problems",
  "Visualising solid shapes",
  "Faces, edges, and vertices",
  "Mensuration",
  "Area of a trapezium",
  "Area of a polygon",
  "Cube and cuboid",
  "Cylinder",
  "Exponents and powers",
  "Laws of exponents (Recap)",
  "Negative exponents",
  "Laws of exponents (More practice)",
  "Numbers in standard form",
  "Factorisation",
  "Factors of a monomial",
  "Factorisation using common factors",
  "Factorisation using identities",
  "Factors of the form (x+a)(x+b)",
  "Dividing polynomials by monomials",
  "Dividing polynomials by polynomials",
  "Introduction to graphs",
  "Coordinates",
  "Distance between points in the first quadrant",
  "Playing with numbers",
  "Test for divisibility",
  "Some more divisibility tests",
  "Class 9 math (India)",
  "Number systems",
  "Irrational numbers",
  "Real numbers and their decimal expansions",
  "Operations on real numbers",
  "Simplifying expressions",
  "Laws of exponents for real numbers",
  "Polynomials",
  "Polynomials in one variable",
  "Zeros of a polynomial",
  "Remainder theorem",
  "Factorisation of polynomials",
  "Multiplying polynomials",
  "Standard identities",
  "Algebraic identities",
  "Coordinate geometry",
  "Cartesian system",
  "Plotting points on cartesian plane",
  "Linear equations in two variables",
  "Solutions of a linear equation",
  "Graph of a linear equation in two variables",
  "Lines and angles",
  "Pairs of angles",
  "Parallel lines and a transversal",
  "Lines parallel to the same line",
  "Angle sum property of a triangle",
  "Proofs: Lines and angles",
  "Triangles",
  "Triangles (review)",
  "Pythagorean theorem",
  "Criteria for congruence of triangles",
  "Proofs: Triangles",
  "Inequalities in a triangle",
  "Quadrilaterals",
  "Kinds of quadrilaterals",
  "Proofs: Parallelograms",
  "Proofs: Rhombus",
  "Proofs: Kite",
  "Areas of parallelograms and triangles",
  "Area of a parallelogram",
  "Area of a triangle",
  "Circles",
  "Circles and its related terms",
  "Angle subtended by a chord/arc of a circle",
  "Perpendicular from the centre to a chord",
  "Cyclic quadrilaterals",
  "Inscribed shapes problem solving",
  "Surface areas and volumes",
  "Heron's formula",
  "Cube, cuboid, and cylinder",
  "Cones and spheres",
  "Statistics",
  "Bar graphs",
  "Histograms",
  "Mean, median, mode, range",
  "Probability",
  "Experimental probability",
  "Probability problems",
  "Class 10 math (math)",
  "Real numbers",
  "Euclid's division algorithm",
  "Fundamental theorem of arithmetic",
  "HCF and LCM",
  "Proofs: Irrational numbers",
  "Rational numbers and their decimal expansions",
  "Polynomials",
  "Geometrical meaning of the zeros of a polynomial",
  "Relationship between zeros and coefficients",
  "Division algorithm for polynomials",
  "Pair of linear equations in two variables",
  "Graphical method",
  "Algebraic methods",
  "Number of solutions algebraically",
  "Equations reducible to linear form",
  "Linear equations word problems",
  "Quadratic equations",
  "Solving equations by factorizing",
  "Solving equations by completing the square",
  "Solving equations using the quadratic formula",
  "Nature of roots",
  "Quadratic equations word problems",
  "Arithmetic progressions",
  "Intro to arithmetic progressions",
  "Common difference of an AP",
  "nth term of an AP",
  "Sum of first n terms of an AP",
  "AP word problems",
  "Triangles",
  "Similarity of triangles",
  "Problems involving similar triangles",
  "Pythagoras theorem",
  "Coordinate geometry",
  "Distance formula",
  "Section  formula",
  "Mid-point formula",
  "Area of a triangle",
  "Introduction to trigonometry",
  "Intro to trigonometric ratios",
  "Reciprocal trigonometric ratios",
  "Trigonometric ratios of some specific angles",
  "Trigonometric ratios of complementary angles",
  "Trigonometric identities",
  "Some applications of trigonometry",
  "One triangle problems",
  "Two triangles problems",
  "Circles",
  "Tangent to a circle",
  "Number of tangents from a point to a circle",
  "Areas related to circles",
  "Perimeter of circular figures",
  "Areas of sector and segment of a circle",
  "Areas of combination of plane figures",
  "Surface areas and volumes",
  "Combination of solids",
  "Conversion of solids",
  "Frustum of a cone",
  "Statistics",
  "Mean, median, mode of grouped data",
  "Ogives",
  "Probability",
  "Probability - a theoretical approach",
  "Independent events",
  "Dependent events",
  "Adding probabilities",
  "Class 11 math (India)",
  "Sets",
  "Introduction to sets",
  "Subsets",
  "Operations on sets",
  "Applications of sets",
  "Relation and functions",
  "Cartesian product of sets",
  "Relations",
  "Domain, codomain and range of relations",
  "What is a function?",
  "Inputs and outputs of a function",
  "Introduction to domain and range",
  "Domain of a function",
  "Range of a function",
  "Piecewise functions",
  "Algebra of real functions",
  "Graph of functions",
  "Solutions to select NCERT problems",
  "Trigonometric functions",
  "Degrees and radians",
  "Unit circle",
  "Trigonometric functions",
  "Trigonometric identities: Symmetry",
  "Trigonometric identities: Sum and differences",
  "Trigonometric equations",
  "Solutions to select NCERT problems",
  "Complex numbers",
  "What are the imaginary numbers?",
  "What are the complex numbers?",
  "Adding and subtracting complex numbers",
  "Multiplying complex numbers",
  "Dividing complex numbers",
  "Absolute value & angle of complex numbers",
  "Polar form of complex numbers",
  "Linear inequalities",
  "Introduction to inequalities",
  "Solutions of linear inequalities in on variable",
  "Inequalities word problems",
  "Graphical solution of linear inequalities in two variables",
  "Solution of system of linear inequalities in two variables",
  "Compound inequalities",
  "Permutations and combinations",
  "Fundamental Principle of Counting",
  "Permutations",
  "Combinations",
  "Binomial theorem",
  "Intro to the Binomial theorem",
  "Sequence and series",
  "Intro to sequence and series",
  "Arithmetic sequences",
  "Arithmetic series",
  "Geometric sequences",
  "Geometric series",
  "Sequence and series word problems",
  "Special series",
  "Straight lines",
  "Two-variable linear equations intro",
  "Slope",
  "Horizontal and vertical lines",
  "x-intercepts and y-intercepts",
  "Applying intercepts and slope",
  "Intro to slope-intercept form",
  "Graphing slope-intercept equations",
  "Writing slope-intercept equations",
  "Point-slope form",
  "Standard form",
  "Summary: Forms of two-variable linear equations",
  "Conic sections",
  "Introduction to conic sections",
  "The features of a circle",
  "Standard equation of a circle",
  "Expanded equation of a circle",
  "Center and radii of an ellipse",
  "Foci of an ellipse",
  "Focus and directrix of a parabola",
  "Introduction to hyperbolas",
  "Hyperbolas not centered at the origin",
  "Identifying conic sections from their equations",
  "Introduction to three dimensional geometry",
  "Coordinates of a point in space",
  "Distance between two points",
  "Section formula",
  "Limits",
  "Limits into",
  "Estimating limits from graph",
  "Estimating limits from tables",
  "Formal definition of limits (epsilon-delta)",
  "Properties of limits",
  "Limits by direct substitution",
  "Limits using algebraic manipulation",
  "Strategy in finding limits",
  "Squeeze theorem",
  "Derivations",
  "Average vs. instantaneous rate of change",
  "Derivative definition",
  "Power rule",
  "More on power rule",
  "Derivatives of polynomial functions",
  "Product rule",
  "Quotient rule",
  "Derivatives of trigonometric functions",
  "Proof videos",
  "Statistics",
  "Measures of central tendency: mean, median and mode",
  "Measures of spread: range, variance, and standard deviation",
  "Other measures of spread: mean absolute deviation",
  "Probability",
  "Random experiments",
  "Events",
  "Probability of events",
  "Solutions to select NCERT problems",
  "Class 12 math (India)",
  "Relations and functions",
  "Types of relations",
  "One-one and onto functions",
  "Composite functions",
  "Intro to inverse functions",
  "Verifying inverse functions by composition",
  "Invertible functions",
  "Binary operations",
  "Solutions to select NCERT problems",
  "Inverse trigonometric functions",
  "Intro to inverse trigonometric functions",
  "Matrices",
  "Introduction to matrices",
  "Adding & subtracting matrices",
  "Multiplying matrices by scalars",
  "Properties of matrix addition & scalar multiplications",
  "Multiplying matrices by matrices",
  "Properties of matrix multiplications",
  "Transpose of a matrix",
  "Elementary matrix row operations",
  "Invertible matrices",
  "Inverse of a matrix by elementary operations",
  "Determinants",
  "Determinants",
  "Properties of determinants",
  "Adjoint and inverse of a matrix using minors and cofactors",
  "Solving equations with inverse matrices",
  "Continuity & differentiablity",
  "Continuity at a point",
  "Review: Limits of combined & composite functions",
  "Continuous functions",
  "Review: Intermediate value theorem",
  "Differentiability",
  "Review: Differentiation basics",
  "Product rule",
  "Quotient rule",
  "Chain rule",
  "Review: Product, quotient, & chain rule",
  "Rational functions differentiation",
  "Radical functions differentiation",
  "Trigonometric functions differentiation",
  "Exponential functions differentiation",
  "Logarithmic functions differentiation",
  "Derivatives capstone",
  "Advanced differentiation",
  "Implicit differentiation introduction",
  "Implicit differentiation (advanced examples)",
  "Inverse trig functions differentiation",
  "Derivatives of inverse functions",
  "Disguised derivatives",
  "Proofs for the derivatives of e^x and ln(x)",
  "Logarithmic differentiation",
  "Review: Advanced differentiation",
  "Higher-order derivatives",
  "Mean value theorem",
  "Playing with graphs (using differentiation)",
  "Critical points",
  "Increasing & decreasing intervals",
  "Relative minima & maxima",
  "Absolute minima & maxima",
  "Review: Increasing/decreasing intervals & extrema",
  "Concavity",
  "Points of inflection",
  "Sketching graphs using calculus",
  "Review: Concavity & points of inflection",
  "Applications of derivatives",
  "Approximations",
  "Related rates",
  "Tangents and normals",
  "Optimization",
  "Applied rates of change",
  "L'Hopital's rule",
  "Review: Derivative applications",
  "Indefinite Integrals",
  "Antiderivatives",
  "Indefinite integrals intro",
  "Indefinite integrals of common functions",
  "Review: Indefinite integrals & antiderivatives",
  "Integration by parts",
  "u-substitution",
  "Reverse chain rule",
  "Partial fraction expansion",
  "Integration using trigonometric identities",
  "Trigonometric substitution",
  "Definite Integrals",
  "Functions defined by integrals",
  "Fundamental theorem of calculus",
  "Fundamental theorem of calculus: chain rule",
  "Definite integral as area",
  "Definite integral properties",
  "Review: Definite integral basics",
  "Definite integral evaluation",
  "Definite integrals of piecewise functions",
  "Challenging definite-integrals",
  "Improper integrals",
  "Riemann sums",
  "Riemann sums with sigma notation",
  "Trapezoidal rule",
  "Definite integral as the limit of a Riemann sum",
  "Review: Riemann sums",
  "Application of integrals",
  "Area under simple curves",
  "Area between two curves",
  "Area defined by polar graphs",
  "Differential equations",
  "Intro to differential equations",
  "Separable equations",
  "Homogeneous equations",
  "Exact equations and integrating factors",
  "Vector basics",
  "Magnitude and direction of vectors",
  "Dot product of vectors",
  "Cross product of vectors",
  "Three dimensional geometry",
  "Direction cosines and direction ratios of a line",
  "Equation of a line",
  "Angle between two lines",
  "Shortest distance between two lines",
  "Equation of a plane",
  "Coplanarity of two lines",
  "Angle between two planes",
  "Distance of a point from a plane",
  "Linea and planes",
  "Advanced topics in planes",
  "Probability",
  "Conditional probability and independence",
  "Bayes theorem",
  "Discrete random variables",
  "Binomial random variables",
  "Binomial mean and standard deviation formulas",
  "More on expected value",
];
