var maths_text = [
  "Course summary",
  "Class 1 math (India)",
  "Class 2 math (India)",
  "Class 3 math (India)",
  "Class 4 math (India)",
  "Class 5 math (India)",
  "Class 6 math (India)",
  "Class 7 math (India)",
  "Class 8 math (India)",
  "Class 9 math (India)",
  "Class 10 math (India)",
  "Class 11 math (India)",
  "Class 12 math (India)",
  "Class 1 math (India)",
  "Number from 1 to 9",
  "Number from 10 to 20",
  "Number from 1 to 100",
  "Geometry and measurement",
  "Class 2 math (India)",
  "Numbers from 1 to 100",
  "Addition and subtraction without regrouping",
  "Addition and subtraction with regrouping",
  "Geometry and measurement",
  "Class 3 math (India)",
  "Numbers from 1 to 1000",
  "Addition and subtraction without regrouping",
  "Addition and subtraction with regrouping",
  "Multiplication",
  "Division",
  "Smart charts",
  "Geometry and measurement",
  "Class 4 math (India)",
  "Addition and subtraction",
  "Multiplication",
  "Division",
  "Smart charts",
  "Halves and quarters",
  "Geometry and measurement",
  "Class 5 math (India)",
  "Addition and subtraction",
  "Multiplication",
  "Division",
  "Parts and wholes",
  "Tenths and Hundredths",
  "Factors and multiples",
  "Smarts charts",
  "How big? How heavy?"
      "Shapes and angles",
  "Area and its boundary",
  "Identify patterns",
  "Class 6 math (India)",
  "Knowing our numbers",
  "Whole numbers",
  "Playing with numbers",
  "Basic geometrical ideas",
  "Understanding elementary shapes",
  "Integers",
  "Fractions",
  "Decimals",
  "Data handling",
  "Mensuration",
  "Algebra",
  "Ratio and proportion",
  "Class 7 math (India)",
  "Integers",
  "Fractions and decimals",
  "Data handling",
  "Simple equations",
  "Lines and angles",
  "The triangle and its properties",
  "Congruence of triangles",
  "Comparing quantities",
  "Rational numbers",
  "Perimeter and area",
  "Exponents and powers",
  "Algebraic expressions",
  "Class 8 math (India)",
  "Rational numbers",
  "Linear equations in one variable",
  "Understanding quadrilaterals",
  "Data handling",
  "Squares and square roots",
  "Cubes and cube roots",
  "Comparing quantities",
  "Algebraic expressions and identities",
  "Visualising solid shapes",
  "Mensuration",
  "Exponents and powers",
  "Factorisation",
  "Introduction to graphs",
  "Playing with numbers",
  "Class 9 math (India)",
  "Number systems",
  "Polynomials",
  "Coordinate geometry",
  "Linear equations in two variables",
  "Lines and angles",
  "Triangles",
  "Quadrilaterals",
  "Areas of parallelograms and triangles",
  "Circles",
  "Surface areas and volumes",
  "Statistics",
  "Probability",
  "Class 10 math (India)",
  "Real numbers",
  "Polynomials",
  "Pair of linear equations in two variables",
  "Quadratic equations",
  "Arithmetic progressions",
  "Triangles",
  "Coordinate geometry",
  "Introduction to trigonometry",
  "Some applications of trigonometry",
  "Circles",
  "Areas related to circles",
  "Surface areas and volumes",
  "Statistics",
  "Probability",
  "Class 11 math (India)",
  "Sets",
  "Relations and functions",
  "Trigonometric functions",
  "Complex numbers",
  "Linear inequalities",
  "Permutations and combinations",
  "Binomial theorem",
  "Sequence and series",
  "Straight lines",
  "Conic sections",
  "Introduction to three dimensional geometry",
  "Limits",
  "Derivatives",
  "Statistics",
  "Probability",
  "Class 12 math (India)",
  "Relations and functions",
  "Inverse trigonometric functions",
  "Matrices",
  "Determinants",
  "Continuity & differentiability",
  "Advanced differentiation",
  "Playing with graphs (using differentiation)",
  "Applications of derivatives",
  "Indefinite Integrals",
  "Definite Integrals",
  "Application of integrals",
  "Differential equations",
  "Vector algebra",
  "Three dimensional geometry",
  "Probability",
  "Class 1 math (India)",
  "Numbers from 1 to 9",
  "Counting small numbers",
  "Comparing small numbers",
  "What is additions?",
  "Making small numbers",
  "Making 10",
  "What is subtraction?",
  "Subtract within 10",
  "Relate addition and subtraction",
  "Addition and subtraction word problems",
  "Numbers from 10 to 20",
  "Counting numbers from 1 to 20",
  "Counting objects",
  "Addition within 20",
  "Subtraction within 20",
  "Equal sign",
  "Missing numbers within 20",
  "Repeated addition",
  "Word problems within 20",
  "Word problems with 'more' and 'fewer'",
  "Numbers from 1 to 100",
  "Counting numbers to 100",
  "Counting by tens",
  "Place value",
  "Comparing 2-digit numbers",
  "Geometry and measurement",
  "Shapes and spaces",
  "Length and size",
  "Class 2 math (India)",
  "Numbers from 1 to 100",
  "Counting numbers to 100",
  "Place value",
  "Comparing 2-digit numbers",
  "Addition and subtraction without regrouping",
  "Adding 1s and 10s",
  "Subtracing 1s and 10s",
  "Adding without regrouping",
  "Subtracing without regrouping",
  "Addition and subtraction using number line",
  "Addition and subtraction with regrouping",
  "Adding with regrouping",
  "Subtracting with regrouping",
  "Addition and subtraction mixed problems",
  "Word problems with 100",
  "'Fewer' and 'More' word problems",
  "Geometry and measurement",
  "Length",
  "Mass",
  "Volume",
  "Class 3 math (India)",
  "Numbers from 1 to 1000",
  "Place value",
  "Comparing 3-digit numbers",
  "Skip counting",
  "Addition and subtraction without regrouping",
  "Adding 1s, 10s and 100s",
  "Subtracting 1s, 10s, and 100s",
  "Adding and subtracting by breaking apart",
  "Adding and subtracting using number line",
  "Addition and subtraction with regrouping",
  "Adding by regrouping",
  "Subtracting by regrouping",
  "Adding and subtracting missing value problems",
  "Addition and subtraction word problems",
  "Multiplication",
  "Intro to multiplication",
  "Multiplication problems",
  "Multiplication word problems",
  "Multiply by 10s",
  "Multiply 2-digit numbers with area model",
  "Division",
  "Intro to division",
  "Divide by 1,2,4,5, or 10",
  "Divide by 3 or 6",
  "Divide by 7, 8, or 9",
  "Division word problems",
  "Smart charts",
  "Picture graphs",
  "Geometry and measurement",
  "Length",
  "Volume",
  "Mass",
  "Class 4 math (India)",
  "Addition and subtraction",
  "3-digit addition",
  "3-digit subtraction",
  "Multiplication",
  "Multiply by using area model",
  "Multiply by using distributive property",
  "Multiply by 1-digit numbers",
  "Multi-digit multiplication",
  "Division",
  "Relate multiplication and division",
  "Division: place value and area",
  "Divide by 1 digit numbrs",
  "Multi digit division (no remainders)",
  "Smart charts",
  "Picture graphs",
  "Bar charts",
  "Halves and quarters",
  "Fractions of shapes",
  "Geometry and measurement",
  "Length",
  "Volume",
  "Mass"
      "Time",
  "Perimeter",
  "Area",
];
